defaults:
  - _self_
  - /callbacks: [checkpoint_every_n_steps, checkpoint_monitor, learning_rate_monitor]
  - /data: openwebtext-split
  - /model: small
  - /strategy: ddp
  - /noise: loglinear
  - /lr_scheduler: constant_warmup

mode: train  # train / ppl_eval / sample_eval
diffusion: absorbing_state
backbone: dit  # dit / dimamba / ar
parameterization: subs  # subs / d3pm / sedd
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False

seed: 1

loader:
  global_batch_size: 512
  eval_global_batch_size: ${.global_batch_size}
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: ${div_up:${.global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  eval_batch_size: ${div_up:${.eval_global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
  num_workers: ${eval:"len(__import__('os').sched_getaffinity(0))"}
  pin_memory: True

sampling:
  predictor: topk_static  # topk_static, ddpm_cache
  steps: 128
  noise_removal: True
  num_sample_batches: 2  # Total samples: `num_gpus` * `loader.eval_batch_size` * num_sample_batches
  num_sample_log: 2
  semi_ar: False
  start_from_scratch: True
  stride_length: 1
  num_strides: 1
  mc_dropout_parallel: True
  generated_seqs_path: ''
  nucleus_p: 1.0
  eta: 0
  num_remask: 0
  sampler: mdlm
  step_on: 0
  step_off: 1024
  random_at_step_off: True
  t_on: 0
  t_off: 0
  loop_steps: 0
  loop_step_on: 1024
  num_remask_loop: 0
  carry_over: True
  alpha_on: 0
  dfm: False
  sample_batch_size: 16
  num_initial_masks: 1024
  num_x0_xt: 1
  num_xs_x0: 1

training:
  ema: 0.9999
  antithetic_sampling: True
  importance_sampling: False
  sampling_eps: 1e-3
  change_of_variables: False
  loss_type: cross_entropy

eval:
  checkpoint_path: ''  # Used to evaluate a checkpoint after training.
  adapter_checkpoint_path: ''  # Used to evaluate an adapter checkpoint after training.
  disable_ema: False
  compute_generative_perplexity: False
  compute_entropy: False
  compute_mauve: False
  compute_success_rate: False
  generate_sample_on_sanity: False
  perplexity_batch_size: 8
  gen_ppl_eval_model_name_or_path: gpt2-large  # gpt2-large, meta-llama/Llama-2-7b-hf
  generate_samples: True

optim:
  weight_decay: 0
  lr: 3e-4
  adapter_lr: 3e-4
  backbone_lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8

adapter:
  enable: False
  backbone: adapter_dit
  n_blocks: 0
  input_type: embedding  # embedding / xt / x0

adapter_training:
  sampling_eps: 1e-3
  tune_backbone: True
  loss_type: prism-loss # prism-loss / token-critic
  reweight_loss: False
  num_demasking_tokens_per_step: 32
  reg_lambda: 0.5

trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  num_nodes: 1
  devices: ${device_count:}
  accumulate_grad_batches: ${div_up:${loader.global_batch_size}, ${eval:${trainer.devices} * ${loader.batch_size} * ${trainer.num_nodes}}}
  gradient_clip_val: 1.0
  precision: 'bf16-mixed'
  num_sanity_val_steps: 2
  max_steps: 1_000_000
  log_every_n_steps: 10
  limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
  limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
  val_check_interval: 10000

wandb:
  project: PRISM
  entity: seunggeun_kim_kr-austin
  notes: training MDM to infernece better
  group: null
  job_type: null
  name: null
  id: ${.name}_${seed}
  tags:
    - ${noise.type}
    - ${data.train}
    - ${data.valid}

hydra:
  run:
    dir: ./outputs/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true

checkpointing:
  # Use custom `save_dir` if, e.g., saving to S3 bucket, otherwise leave this parameter as is
  save_dir: ${cwd:}
  # Note: `checkpoints` path should correspond to `checkpoint_every_n_steps.dirpath`
  resume_from_ckpt: true
  resume_ckpt_path: ${.save_dir}/checkpoints/last.ckpt
